name: Run tests for debugging sigabrt

on: [pull_request]

jobs:

  testing:
    runs-on: ubuntu-20.04
    container: python:3.9
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements_tests.txt

    - name: Download spatialite on Linux
      run: |
        apt-get update
        apt-get install -y libsqlite3-mod-spatialite

    - name: Build
      run: |
        pip install -e .

    - name: Runs test
      run: python -m pytest
